// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  firebase: {
    projectId: 'ejercicio-angular-76065',
    appId: '1:546235866762:web:8e08cf2b99598c7ba9d773',
    storageBucket: 'ejercicio-angular-76065.appspot.com',
    locationId: 'us-central',
    apiKey: 'AIzaSyAD0u08bshsEBJOYPomPw9VhghAQOskCyo',
    authDomain: 'ejercicio-angular-76065.firebaseapp.com',
    messagingSenderId: '546235866762',
  },
  production: true,
  version: env['npm_package_version'],
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],
};
